### ISSUE TITLE
[VPC] Deconstruct cloudformation template

### ISSUE THREAD

**Issue by tinnightcap** [Nubisproject/nubis-vpc#27]
In order to simplify and encapsulate the contained logic this template needs to be deconstructed into logical and discrete components. My thinking at this point is to:

 - [ ] Break out Private Subnet #25
 - [ ] Break out Public Subnet #24
 - [ ] Break out VPN Logic #22
 - [ ] Simplify Mappings #23 
 - [ ] Create account container template #30 

Finally, as all of these will be nested stacks it might make sense to move the vpn template into the nested stacks repository to minimize the number of repositories we maintain and release. More discussion on this point after the above work has been completed.

P.S. One additional simplification in maintaining deployments is around NAT AMI-IDs. This is a non-blocking enhancement and therefore will not be a part of this tracker. Further details can be found in issue #26.

**Comment by gozer** [comment]
This has been closed by Nubisproject/nubis-stacks#99
